# Generated by Django 5.2.16 on 2026-09-08 08:47

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_documentattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentattachment',
            name='file',
            field=models.FileField(storage=core.models.attachment_storage, upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg']), core.models.validate_document_attachment_size]),
        ),
    ]
