name: Mirror to GitHub

on:
  push:
    branches: [ "main" ]

jobs:
  mirror-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitHub
        run: |
          git remote add mirror https://${{ secrets.MIRROR_USER }}:${{ secrets.MIRROR_TOKEN }}@github.com/${{ secrets.MIRROR_REPO }}.git
          git push mirror main --force
